 ## <span style= "color:red">Initializing Different Types of Array

In [1]:
import numpy as np

In [2]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
# All Zeros Matrix
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
#All 1s Matrices
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.ones((4,2,2))  # Concept: ya 4 ki index array ha 
                # or is m 2 rows and 2 columns han

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [6]:
# Any Other Number   # is sy hm ksi bi no. ki array bna skty han
np.full((3,6) , 19 )

array([[19, 19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19, 19]])

In [7]:
#Any Other Number (full_like)
a=[[1,8,3,2] ,[5,6,7,2]]
print(a)
np.full_like(a, 6)

[[1, 8, 3, 2], [5, 6, 7, 2]]


array([[6, 6, 6, 6],
       [6, 6, 6, 6]])

In [8]:
# Genrate Random Decimal no  
   # sary No zero sy 1 Tak Hon gy  koi Bi 1 sy bada ni ho ga
   
   # ya floating point no han
    
np.random.rand(3,2) # ya uniform distribution ha ya 0 sy 1 tak hoti ha  

array([[0.4295055 , 0.03417453],
       [0.72241976, 0.7665383 ],
       [0.37781014, 0.52446516]])

In [9]:
# ya normal distribution ha  -1 sy 1 ya 1 sy badi bi ni ho skti

np.random.randn(3,2) 


array([[-0.20368762,  1.99916982],
       [ 0.0509179 ,  0.86284582],
       [ 0.56800733, -0.10532438]])

In [10]:
# random integer vales         

# integer no generate ho rhy han

np.random.randint(-4,7, size=(3,3))    # Khud sy data genrate kr rha ha

array([[-1,  0,  0],
       [-1, -3, -2],
       [-4,  6,  2]])

In [11]:
# The identity Matrix
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [12]:
# The identity Matrix
#np.identity(5) # eye and identity have same functionality 
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
# Repeat any Array
arr= np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)


[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [14]:
output =np.ones((5,4))
print(output)
z= np.zeros((2,3))
z[1,2]=5
print(z)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 5.]]


### Dot product is  Most Important  concept for Deep learning 

- (3,3) (3,2) # agr last  wal 2 no same hon to ya multiply ho skty han

- (3,3) (2,3) # ya ,ultiply ni ho skty  [ 1st m Col* 2nd m row  ]


In [15]:
# Dot Product

a=([[11,33],[2,3]])
b=([[1,2,],[11,21]])
np.dot(a,b)   

array([[374, 715],
       [ 35,  67]])

## arange

- Return Evenly spaced values with in a given interval

In [16]:
np.arange(0,8)  # 8 is Excluded

array([0, 1, 2, 3, 4, 5, 6, 7])

In [17]:
np.arange(0,8,2) # with Step size   

array([0, 2, 4, 6])

### linspace
- Return evenly spaced numbers over a spacified interval

In [18]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [19]:
np.linspace(0,10,50)   # Mot be evenly spaced

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [20]:
np.eye(4)  # eye is like identity matrix , its wirkis same as identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## max, min, argmax, argmin
- These are useful methods for finiding max and min values,<br>
or to find there index locaions unsing argmin , or argmax

In [21]:
arr=np.array([11,12,23,44,5,26,37,38,29,28])

In [22]:
arr

array([11, 12, 23, 44,  5, 26, 37, 38, 29, 28])

In [23]:
arr.max()

44

In [24]:
arr.min()

5

In [25]:
arr.argmax()  # Return Highest index

3

In [26]:
arr.argmin() # return minimum Index

4

### shape
- **Shape is an atribute that arrays have ( Not a Method):**

In [27]:
# Vector
arr.shape

(10,)

In [28]:
# Notice the two sets of Brackets  
# hm 25 m kr ry thy but total element hmary pass 10 thy
arr.reshape(1,10)

array([[11, 12, 23, 44,  5, 26, 37, 38, 29, 28]])

### Linear Algebra

In [29]:
c=np.eye(4)
c


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
# find the determinent

c=np.identity(3)
np.linalg.det(c) 

1.0

### Standard Diviation
- In uniform Distribution standard diviation will be from 0 to 1
- in Normal  Distribution standard diviation will be from -1 to 1

In [31]:
s=np.array([[11,33,8],[12,23,13]])
s

array([[11, 33,  8],
       [12, 23, 13]])

In [32]:
# Standard Diviation
np.std(s)

8.65383665716478

In [33]:
#variance
np.var(s)

74.88888888888889

## Miscellaneous
- **Load Data From Files**

In [34]:
file=np.genfromtxt('data.txt', delimiter=',')

In [35]:
print(file) # These are Float Numbers 

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


In [36]:
# Convert the float numbrs into int. numbers
file = file.astype('int32')
print(file)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


# Great Job!